sudo: false
language: python
matrix:
  include:
    - os: linux
      python: 3.5
      env: TOX_ENV=py35
    - os: linux
      python: 3.6
      env: TOX_ENV=py36
    - os: linux
      python: 3.7
      env: TOX_ENV=py37
    - os: linux
      python: pypy
      env: TOX_ENV=pypy
    - os: osx
      osx_image: xcode11.2
      language: generic
      env: TOX_ENV=py37
    - os: linux
      python: 3.7
      env: TOX_ENV=flake8
    - os: linux
      python: 3.7
      env: TOX_ENV=coverage
install:
  - pip install Babel tox
script: tox -e $TOX_ENV
